Improve SCALE file support
Improves SCALE file support by allowing the skipping of process types.
If a Procfile entry does not have an entry in the SCALE file, or if
it has an entry with a num processes of 0 (zero), then it will be skipped
and no supervisord config will not be generated for it.

The default behavior of runinng one process for each entry in the Procfile
remains when a SCALE file is not defined.

diff --git a/lib/procfile-to-supervisord b/lib/procfile-to-supervisord
--- a/lib/procfile-to-supervisord
+++ b/lib/procfile-to-supervisord
@@ -18,6 +18,10 @@ if [ ! -f "$PROCFILE" ]; then
   exit 1
 fi
 
+function log_debug() {
+  echo "$@" 1>&2
+}
+
 function gen_supervisor_conf () {
 cat << EOF
 [supervisord]
@@ -64,8 +68,12 @@ do
   if [ -f "$SCALEFILE" ]; then
     SCALE=$(grep "$NAME=" "$SCALEFILE")
     NUM_PROCS=${SCALE#*=}
+    if [[ "$SCALE" == "" ]] || [[ "$NUM_PROCS" -eq 0 ]]; then
+      log_debug "NOTE: Process $NAME will not execute (num proceses is zero)"
+      continue
+    fi
     if [ ! "$NUM_PROCS" -ge 1 ]; then
-      echo "Invalid scale line for process $NAME: $SCALE" 1>&2
+      log_debug "Invalid scale line for process $NAME: $SCALE" 1>&2
       exit 1
     fi
   fi
